#app options
FRAME_INIT_WIDTH = 1920
FRAME_INIT_HEIGHT = 1080
FRAME_INIT_BACKGROUND_COLOR = "#00134d"
FRAME_INIT = {"width":FRAME_INIT_WIDTH,"height":FRAME_INIT_HEIGHT,"bg":FRAME_INIT_BACKGROUND_COLOR}
FRAME_INIT_PX = 10
FRAME_INIT_PY = 710

#cell options
CELL_INIT_SIZE = 10
CELLS_X_INIT = 32
CELLS_Y_INIT = 32

#canvas options
CANVAS_INIT_WIDTH = CELLS_X_INIT * CELL_INIT_SIZE + 2
CANVAS_INIT_HEIGHT = CELLS_Y_INIT * CELL_INIT_SIZE + 2
CANVAS_INIT_PX = 0
CANVAS_INIT_PY = 0

#grid options
GRID_INIT_WIDTH = 606
GRID_INIT_HEIGHT = 606
GRID_INIT_BACKGROUND_COLOR = "#e6e6e6"
GRID_INIT_BORDER_SIZE = 0
GRID_INIT_HIGHLIGHTTHICKNESS = 0
GRID_INIT={"width":GRID_INIT_WIDTH, "height":GRID_INIT_HEIGHT, "bg":GRID_INIT_BACKGROUND_COLOR, "bd":GRID_INIT_BORDER_SIZE, "highlightthickness":GRID_INIT_HIGHLIGHTTHICKNESS}
GRID_INIT_PX = 611
GRID_INIT_PY = 5

#panel options
PANEL_INIT_WIDTH = 1887
PANEL_INIT_HEIGHT = 321
PANEL_INIT_BACKGROUND_COLOR = "#4d4d4d"
PANEL_INIT_BORDER_SIZE = 0
PANEL_INIT_HIGHLIGHTTHICKNESS = 0
PANEL_INIT_RELIEF = "flat"
PANEL_INIT = {"width":PANEL_INIT_WIDTH, "height":PANEL_INIT_HEIGHT, "bg":PANEL_INIT_BACKGROUND_COLOR, "bd":PANEL_INIT_BORDER_SIZE, "highlightthickness":PANEL_INIT_HIGHLIGHTTHICKNESS, "relief":PANEL_INIT_RELIEF}
PANEL_INIT_PX = 5
PANEL_INIT_PY = 659

#buttons positions
SELECT_BUTTONS=0
ADD_PART_BUTTONS=1
DELETE_PART_BUTTONS=2
DELETE_MAIN_BUTTONS=3

#element position
LAST_ELEMENT = -1

#board options
BOARD_INIT_WIDTH = 111 * 16
BOARD_INIT_HEIGHT = 321
BOARD_INIT_BACKGROUND_COLOR = "#e6e6e6"
BOARD_INIT_BORDER_SIZE = 0
BOARD_INIT_HIGHLIGHTTHICKNESS = 0
BOARD_INIT = {"width":BOARD_INIT_WIDTH, "height":BOARD_INIT_HEIGHT, "bg":BOARD_INIT_BACKGROUND_COLOR, "bd":BOARD_INIT_BORDER_SIZE, "highlightthickness":BOARD_INIT_HIGHLIGHTTHICKNESS}
BOARD_INIT_PX = 111
BOARD_INIT_PY = 0

#main options
MAIN_INIT_WIDTH=111
MAIN_INIT_HEIGHT=308
MAIN_INIT_BACKGROUND_COLOR="#666666"
MAIN_INIT_BORDER_SIZE=0
MAIN_INIT_HIGHLIGHTTHICKNESS=1
MAIN_INIT={"width":MAIN_INIT_WIDTH,"height":MAIN_INIT_HEIGHT,"bg":MAIN_INIT_BACKGROUND_COLOR,"bd":MAIN_INIT_BORDER_SIZE,"highlightthickness":MAIN_INIT_HIGHLIGHTTHICKNESS}

#anim options
ANIM_INIT_WIDTH = 601
ANIM_INIT_HEIGHT = 650
ANIM_INIT_BACKGROUND_COLOR = "#666666"
ANIM_INIT_BORDER_SIZE = 0
ANIM_INIT_HIGHLIGHTTHICKNESS = 0
ANIM_INIT={"width":ANIM_INIT_WIDTH,"height":ANIM_INIT_HEIGHT,"bg":ANIM_INIT_BACKGROUND_COLOR,"bd":ANIM_INIT_BORDER_SIZE,"highlightthickness":ANIM_INIT_HIGHLIGHTTHICKNESS}
ANIM_INIT_PX = 5
ANIM_INIT_PY = 5

#anim canvas
ANIM_CANVAS_INIT_WIDTH = 601
ANIM_CANVAS_INIT_HEIGHT = 598
ANIM_CANVAS_INIT_BACKGROUND_COLOR = "#00ff00"
ANIM_CANVAS_INIT_BORDER_SIZE = 0
ANIM_CANVAS_INIT_HIGHLIGHTTHICKNESS = 0
ANIM_CANVAS_INIT={"width":ANIM_CANVAS_INIT_WIDTH,"height":ANIM_CANVAS_INIT_HEIGHT,"bg":ANIM_CANVAS_INIT_BACKGROUND_COLOR,"bd":ANIM_CANVAS_INIT_BORDER_SIZE,"highlightthickness":ANIM_CANVAS_INIT_HIGHLIGHTTHICKNESS}
ANIM_CANVAS_INIT_PX = 0
ANIM_CANVAS_INIT_PY = 0


#=================CONSTANTS==================
TRANSPARENT_COLOR_RGB = (254,254,254)
TRANSPARENT_COLOR_HEXA = "#fefefe"
TRANSPARENT_COLOR_RGBA = (254,254,254,255)

#pen options
PEN_INIT_LEFT_COLOR = (255,0,0)
PEN_INIT_RIGHT_COLOR = (0,0,255)

#mouse button options
LEFT_BUTTON = 0
RIGHT_BUTTON = 1
PREV_LEFT_BUTTON = 2

#colors options
RGB = 0
HEXA = 1

#grid size options
GRID_MAX = 31
GRID_MIN = 0

#fps options
MS_IN_S = 1000
FPS_INIT = 5

#tools options
PEN = 0
ERASER = 1
CIRCLE = 2
SPRAY = 3

#controller options
INDEX_INIT = 0
PX_INIT = 0
PY_INIT = 0

#ZOOM 
ZOOM_IN = 1
ZOOM_OUT = -1
MIN_ZOOM = 1
MAX_ZOOM = 40

#scrollbar options
SCROLLBAR_X_PX = 611
SCROLLBAR_X_PY = 611
SCROLLBAR_X_WIDTH = 619
SCROLLBAR_X_HEIGHT = 13
SCROLLBAR_Y_PX = 1217
SCROLLBAR_Y_PY = 5
SCROLLBAR_Y_WIDTH = 13
SCROLLBAR_Y_HEIGHT = 606

#toplevel
NEW_PROJECT_INIT_WIDTH = 300
NEW_PROJECT_INIT_HEIGHT = 400
NEW_PROJECT_PX = (FRAME_INIT_WIDTH - NEW_PROJECT_INIT_WIDTH) // 2
NEW_PROJECT_PY = 200
NEW_PROJECT_INIT_SIZE_X = 32
NEW_PROJECT_INIT_SIZE_Y = 32

#opening_project
PROJECT_NAME = 0
PROJECT_SIZE = 1
PROJECT_IMAGES = 2
